_target_: navsim.agents.deepseek.deepseek_agent.DeepSeekAgent
_convert_: 'all'

config:
  _target_: navsim.agents.deepseek.deepseek_config.DeepSeekConfig
  _convert_: 'all'

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5