_target_: navsim.agents.deepseek.gpt_agent.GPTAgent
_convert_: 'all'

config:

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5